# k3d cluster configuration
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab
servers: 1
agents: 2
image: rancher/k3s:v1.28.5-k3s1 # Pinned version for stability
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  # k3s:
  #   extraArgs:
  #     - arg: --disable=traefik
  #       nodeFilters:
  #         - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true