# Default values for monitoring chart
# This is a starting point, customize as needed.

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      storageClass: "local-path" # Or your preferred storage class
      size: 8Gi

grafana:
  enabled: true
  adminPassword: "changeme" # CHANGE THIS!
  persistence:
    enabled: true
    storageClassName: "local-path" # Or your preferred storage class
    size: 2Gi
  ingress:
    enabled: false # Set to true if you want to expose Grafana via Ingress
    # hosts:
    #   - grafana.example.com
    # tls: []

# Other components like Alertmanager, node-exporter, etc. can be added here
# alertmanager:
#   enabled: false
# nodeExporter:
#   enabled: true
# kubeStateMetrics:
#   enabled: true
