# Helm Values for HashiCorp Vault (Development Mode for Initial Setup)
# Chart Source: https://helm.releases.hashicorp.com
# Chart Version: (Specify a version later if needed, e.g., 0.27.0)

global:
  enabled: true
  namespace: vault # Deploy into the 'vault' namespace

injector:
  enabled: false # We'll use External Secrets Operator, not the Vault injector for now

server:
  # --- Development Mode ---
  # Run Vault in development mode. Single node, in-memory storage (but Helm might still create PVC), auto-unsealed.
  # WARNING: NOT FOR PRODUCTION. Easy for local testing.
  dev:
    enabled: true

  # --- Production Mode (Example - Disabled for now) ---
  # replicas: 1 # Start with 1 for non-HA local setup
  # ha:
  #   enabled: false # Disable HA for single-node local setup
  # dataStorage:
  #   enabled: true
  #   size: 1Gi # Small size for local testing
  #   storageClass: local-path # Use our local path provisioner
  # auditStorage:
  #   enabled: false # Disable audit storage for simplicity initially

  # --- Common Settings ---
  ui:
    enabled: true
    serviceType: "ClusterIP" # Use ClusterIP and port-forward locally
    # serviceNodePort: null
    # externalPort: 8200

# Standalone mode (alternative to global settings, often used for simpler setups)
# We are using the global settings above, so keep this minimal or commented out
# standalone:
#   enabled: false

# UI settings (redundant if global.ui is set, but sometimes needed depending on chart version)
ui:
  enabled: true
  serviceType: "ClusterIP"

# Data storage persistence (even in dev mode, chart might require PVC definition)
dataStorage:
  enabled: true
  size: 1Gi
  storageClass: local-path