# Helm Values for External Secrets Operator (ESO)
# Chart Source: https://charts.external-secrets.io
# Chart Version: (Specify a version later if needed, e.g., 0.9.9)

# Deploy into the 'external-secrets' namespace
namespace: external-secrets
createNamespace: true # Have Helm create the namespace

installCRDs: true # ESO requires CRDs to be installed

# Default settings are usually sufficient for a basic setup.
# We don't need to configure specific secret backends here;
# that's done via ClusterSecretStore/SecretStore resources later.

# Example: Adjust replicas, resources if needed (defaults are fine for now)
# replicaCount: 1
# resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

# Service account settings (defaults are usually fine)
# serviceAccount:
#   create: true
#   name: ""

# RBAC settings (defaults are usually fine)
# rbac:
#   create: true

# Enable Prometheus metrics endpoint if needed later
# prometheus:
#   enabled: false
#   service:
#     port: 8080

# Enable webhook endpoint validation (recommended)
webhook:
  port: 9443

# Enable cert controller for managing webhook certificates (recommended)
certController:
  create: true

# Leader Election settings (defaults are usually fine)
# leaderElect: true