apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This Application resource itself lives in the argocd namespace
  name: local-path-provisioner
  namespace: argocd
  # Ensures this app is deleted cleanly when the root app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the manifests for local-path-provisioner
  source:
    repoURL: https://github.com/dasdevrishi/homelab.git # Inherited from root, but good practice to specify
    targetRevision: HEAD
    path: infrastructure/storage/local-path-provisioner # Points to the manifest(s) for the provisioner

  # Destination where the provisioner resources will be deployed
  destination:
    server: https://kubernetes.default.svc # Target the same cluster
    # The standard local-path-provisioner manifest creates its own namespace
    # Use the namespace defined within its own manifests (typically 'local-path-storage')
    # Argo CD doesn't need to define it here if the manifest does, but CreateNamespace=true handles it.
    namespace: local-path-storage

  # Sync policy: Automatic sync, prune resources, self-heal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Ensure the namespace is created if it doesn't exist
      - CreateNamespace=true 