apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd # Deploy this Application resource into the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Source for the ESO Helm chart
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.9 # Specify a stable chart version (check for latest)

    # Point Argo CD to the values file within *your* Git repository
    helm:
      valueFiles:
        # Path relative to the root of *your* Git repo
        - $values/infrastructure/secrets/external-secrets-operator/helm-values.yaml

  # Override the source repo for the values file location
  # This tells Argo CD where to find the helm-values.yaml file
  # IMPORTANT: Replace with your actual Git repo URL
  sources:
    - repoURL: https://github.com/dasdevrishi/homelab.git
      targetRevision: HEAD
      ref: values # Reference name for the values repo source

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets # Deploy ESO into the 'external-secrets' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Allow Argo CD to create the namespace